### ISSUE TITLE
display_plan is not implemented

### ISSUE THREAD

**Issue by zwhe99** [MandiZhao/robot-collab#5]
Can you take a look at this?

```python
Traceback (most recent call last):
  File "run_dialog.py", line 494, in <module>
    main(args)
  File "run_dialog.py", line 463, in main
    runner.run(args)
  File "run_dialog.py", line 380, in run
    self.one_run(run_id)
  File "run_dialog.py", line 223, in one_run
    self.display_plan(plan, save_name=f"vis_llm_plan_{i}", save_dir=step_dir)
  File "run_dialog.py", line 156, in display_plan
    raise NotImplementedError
NotImplementedError
```

**Comment by zwhe99** [comment]
I got the following error when enabling `--skip_display`.

```python
INFO:root:Stesp: 0 Plan success: True, reason: ReasonDirect_time1.5149331092834473_iter1
INFO:root:Execute the plan for 43 steps
Traceback (most recent call last):
  File "run_dialog.py", line 494, in <module>
    main(args)
  File "run_dialog.py", line 463, in main
    runner.run(args)
  File "run_dialog.py", line 380, in run
    self.one_run(run_id)
  File "run_dialog.py", line 273, in one_run
    obs, reward, done, info = env.step(sim_action, verbose=1)
  File "/Users/zwhe/GitRepo/robot-collab/rocobench/envs/base_env.py", line 646, in step
    if error_dict['error'] < self.error_threshold and step > self.render_freq * 2:
IndexError: invalid index to scalar variable.
```

**Comment by BrahamVictor** [comment]
I had the same problem, have you solved it yet?

**Comment by zwhe99** [comment]
Not yet

Katuwawala ***@***.***>于2023年9月10日 周日17:11写道：

**Comment by MandiZhao** [comment]
hi @zwhe99 @BrahamVictor ! sorry for the late reply, the issue should be fixed in this commit: https://github.com/MandiZhao/robot-collab/commit/12b8dc9f2cc34a59cca48aae05df52782aea0c49, please let me know if you are able to run the script now

**Comment by MandiZhao** [comment]
also, check out this commit for (preliminary) code for enabling display_plan: https://github.com/MandiZhao/robot-collab/commit/9943870298e650de7ff1f9231ed279b35f196ddc, it requires install open3d, and basically shows the plan and the workspace as a voxelized 3D scene
